<?php

/*
 Where the MySQL server is. Usually "localhost" or "127.0.0.1" Check your web hosting provider
 instructions.
 */
$host = "localhost";


/*
 Database user name
 Change this to your database user name
 */
$user = "worthdata";


/*
 Database user password
 Change this to your password
 */
$password = "barcode";


/*
 This is the name of the database that contains the Connection Host tables the database.
 You should either use a database that already exists on your host or make one to hold the
 ConnectionHost tables. If you want to use an existing databse and just add the ConnectionHost
 tables to it, change this to '$database = "mydatabasename"'
 */
$database = "worthdata_termrouter";

?>
